const allInfoBooks = [
  {
    shortNameJs1: "Gen",
    shortNameJs2: "GEN",
    shortNameRus: "Быт.",
    fullNameRus: "Бытие",
  },
  {
    shortNameJs1: "Ex",
    shortNameJs2: "EXO",
    shortNameRus: "Исх.",
    fullNameRus: "Исход",
  },
  {
    shortNameJs1: "Lev",
    shortNameJs2: "LEV",
    shortNameRus: "Лев.",
    fullNameRus: "Левит",
  },
  {
    shortNameJs1: "Num",
    shortNameJs2: "NUM",
    shortNameRus: "Числ.",
    fullNameRus: "Числа",
  },
  {
    shortNameJs1: "Deut",
    shortNameJs2: "DEU",
    shortNameRus: "Втор.",
    fullNameRus: "Второзаконие",
  },
  {
    shortNameJs1: "Josh",
    shortNameJs2: "JOS",
    shortNameRus: "Ис.Нав.",
    fullNameRus: "Иисус Навин",
  },
  {
    shortNameJs1: "Judg",
    shortNameJs2: "JDG",
    shortNameRus: "Суд.",
    fullNameRus: "Судеи",
  },
  {
    shortNameJs1: "Ru",
    shortNameJs2: "RUT",
    shortNameRus: "Руфь.",
    fullNameRus: "Руфь",
  },
  {
    shortNameJs1: "1 Sam",
    shortNameJs2: "1SA",
    shortNameRus: "1Цар.",
    fullNameRus: "1 Царств",
  },
  {
    shortNameJs1: "2 Sam",
    shortNameJs2: "2SA",
    shortNameRus: "2Цар.",
    fullNameRus: "2 Царств",
  },
  {
    shortNameJs1: "1 Ki",
    shortNameJs2: "1KI",
    shortNameRus: "3Цар.",
    fullNameRus: "3 Царств",
  },
  {
    shortNameJs1: "2 Ki",
    shortNameJs2: "2KI",
    shortNameRus: "4Цар.",
    fullNameRus: "4 Царств",
  },
  {
    shortNameJs1: "1 Chron",
    shortNameJs2: "1CH",
    shortNameRus: "1Пар.",
    fullNameRus: "1 Паралипоменон",
  },
  {
    shortNameJs1: "2 Chron",
    shortNameJs2: "2CH",
    shortNameRus: "2Пар.",
    fullNameRus: "2 Паралипоменон",
  },
  {
    shortNameJs1: "Ezra",
    shortNameJs2: "EZR",
    shortNameRus: "Езр.",
    fullNameRus: "Ездра",
  },
  {
    shortNameJs1: "Neh",
    shortNameJs2: "NEH",
    shortNameRus: "Неем.",
    fullNameRus: "Неемия",
  },
  {
    shortNameJs1: "Esth",
    shortNameJs2: "EST",
    shortNameRus: "Эсф.",
    fullNameRus: "Есфирь",
  },
  {
    shortNameJs1: "Job",
    shortNameJs2: "JOB",
    shortNameRus: "Иов.",
    fullNameRus: "Иов",
  },
  {
    shortNameJs1: "Ps",
    shortNameJs2: "PSA",
    shortNameRus: "Пс.",
    fullNameRus: "Псалтирь",
  },
  {
    shortNameJs1: "Prov",
    shortNameJs2: "PRO",
    shortNameRus: "Притч.",
    fullNameRus: "Притчи",
  },
  {
    shortNameJs1: "Ecc",
    shortNameJs2: "ECC",
    shortNameRus: "Эккл.",
    fullNameRus: "Екклесиаст",
  },
  {
    shortNameJs1: "SOS",
    shortNameJs2: "SOS",
    shortNameRus: "Песн.",
    fullNameRus: "Песни Песней",
  },
  {
    shortNameJs1: "Isa",
    shortNameJs2: "ISA",
    shortNameRus: "Ис.",
    fullNameRus: "Исаия",
  },
  {
    shortNameJs1: "Jer",
    shortNameJs2: "JER",
    shortNameRus: "Иер.",
    fullNameRus: "Иеремия",
  },
  {
    shortNameJs1: "Lam",
    shortNameJs2: "LAM",
    shortNameRus: "Плач.",
    fullNameRus: "Плач Иеремии",
  },
  {
    shortNameJs1: "Eze",
    shortNameJs2: "EZE",
    shortNameRus: "Иез.",
    fullNameRus: "Иезекииль",
  },
  {
    shortNameJs1: "Dan",
    shortNameJs2: "DAN",
    shortNameRus: "Дан.",
    fullNameRus: "Даниил",
  },
  {
    shortNameJs1: "Hos",
    shortNameJs2: "HOS",
    shortNameRus: "Ос.",
    fullNameRus: "Осия",
  },
  {
    shortNameJs1: "Joel",
    shortNameJs2: "JOE",
    shortNameRus: "Иоил.",
    fullNameRus: "Иоиль",
  },
  {
    shortNameJs1: "Amos",
    shortNameJs2: "AMO",
    shortNameRus: "Амос.",
    fullNameRus: "Амос",
  },
  {
    shortNameJs1: "Obad",
    shortNameJs2: "OBA",
    shortNameRus: "Авд.",
    fullNameRus: "Авдий",
  },
  {
    shortNameJs1: "Jon",
    shortNameJs2: "JON",
    shortNameRus: "Ион.",
    fullNameRus: "Иона",
  },
  {
    shortNameJs1: "Micah",
    shortNameJs2: "MIC",
    shortNameRus: "Мих.",
    fullNameRus: "Михей",
  },
  {
    shortNameJs1: "Nah",
    shortNameJs2: "NAH",
    shortNameRus: "Наум.",
    fullNameRus: "Наум",
  },
  {
    shortNameJs1: "Hab",
    shortNameJs2: "HAB",
    shortNameRus: "Авв.",
    fullNameRus: "Аввакум",
  },
  {
    shortNameJs1: "Zeph",
    shortNameJs2: "ZEP",
    shortNameRus: "Соф.",
    fullNameRus: "Софония",
  },
  {
    shortNameJs1: "Hag",
    shortNameJs2: "HAG",
    shortNameRus: "Агг.",
    fullNameRus: "Аггей",
  },
  {
    shortNameJs1: "Zech",
    shortNameJs2: "ZEC",
    shortNameRus: "Зах.",
    fullNameRus: "Захария",
  },
  {
    shortNameJs1: "Mal",
    shortNameJs2: "MAL",
    shortNameRus: "Мал.",
    fullNameRus: "Малахия",
  },
  {
    shortNameJs1: "Matt",
    shortNameJs2: "MAT",
    shortNameRus: "Мф.",
    fullNameRus: "От Матфея",
  },
  {
    shortNameJs1: "Mark",
    shortNameJs2: "MAR",
    shortNameRus: "Мк.",
    fullNameRus: "От Марка",
  },
  {
    shortNameJs1: "Luke",
    shortNameJs2: "LUK",
    shortNameRus: "Лк.",
    fullNameRus: "От Луки",
  },
  {
    shortNameJs1: "John",
    shortNameJs2: "JOH",
    shortNameRus: "Ин.",
    fullNameRus: "От Иоанна",
  },
  {
    shortNameJs1: "Acts",
    shortNameJs2: "ACT",
    shortNameRus: "Деян.",
    fullNameRus: "Деяния апостолов",
  },
  {
    shortNameJs1: "Rom",
    shortNameJs2: "ROM",
    shortNameRus: "Рим.",
    fullNameRus: "Римлянам",
  },
  {
    shortNameJs1: "1 Cor",
    shortNameJs2: "1CO",
    shortNameRus: "1Кор.",
    fullNameRus: "1 Коринфянам",
  },
  {
    shortNameJs1: "2 Cor",
    shortNameJs2: "2CO",
    shortNameRus: "2Кор.",
    fullNameRus: "2 Коринфянам",
  },
  {
    shortNameJs1: "Gal",
    shortNameJs2: "GAL",
    shortNameRus: "Гал.",
    fullNameRus: "Галатам",
  },
  {
    shortNameJs1: "Eph",
    shortNameJs2: "EPH",
    shortNameRus: "Эф.",
    fullNameRus: "Ефесянам",
  },
  {
    shortNameJs1: "Phil",
    shortNameJs2: "PHP",
    shortNameRus: "Флп.",
    fullNameRus: "Филиппийцам",
  },
  {
    shortNameJs1: "Col",
    shortNameJs2: "COL",
    shortNameRus: "Кол.",
    fullNameRus: "Колоссянам",
  },
  {
    shortNameJs1: "1 Thess",
    shortNameJs2: "1TH",
    shortNameRus: "1Фес.",
    fullNameRus: "1 Фессалоникийцам",
  },
  {
    shortNameJs1: "2 Thess",
    shortNameJs2: "2TH",
    shortNameRus: "2Фес.",
    fullNameRus: "2 Фессалоникийцам",
  },
  {
    shortNameJs1: "1 Tim",
    shortNameJs2: "1TI",
    shortNameRus: "1Тим.",
    fullNameRus: "1 Тимофею",
  },
  {
    shortNameJs1: "2 Tim",
    shortNameJs2: "2TI",
    shortNameRus: "2Тим.",
    fullNameRus: "2 Тимофею",
  },
  {
    shortNameJs1: "Titus",
    shortNameJs2: "TIT",
    shortNameRus: "Тит.",
    fullNameRus: "Титу",
  },
  {
    shortNameJs1: "Phm",
    shortNameJs2: "PHM",
    shortNameRus: "Флм.",
    fullNameRus: "Филимону",
  },
  {
    shortNameJs1: "Heb",
    shortNameJs2: "HEB",
    shortNameRus: "Евр.",
    fullNameRus: "Евреям",
  },
  {
    shortNameJs1: "Jas",
    shortNameJs2: "JAM",
    shortNameRus: "Иак.",
    fullNameRus: "Иакова",
  },
  {
    shortNameJs1: "1 Pet",
    shortNameJs2: "1PE",
    shortNameRus: "1Петр.",
    fullNameRus: "1 Петра",
  },
  {
    shortNameJs1: "2 Pet",
    shortNameJs2: "2PE",
    shortNameRus: "2Петр.",
    fullNameRus: "2 Петра",
  },
  {
    shortNameJs1: "1 John",
    shortNameJs2: "1JO",
    shortNameRus: "1Ин.",
    fullNameRus: "1 Иоанна",
  },
  {
    shortNameJs1: "2 John",
    shortNameJs2: "2JO",
    shortNameRus: "2Ин.",
    fullNameRus: "2 Иоанна",
  },
  {
    shortNameJs1: "3 John",
    shortNameJs2: "3JO",
    shortNameRus: "3Ин.",
    fullNameRus: "3 Иоанна",
  },
  {
    shortNameJs1: "Jude",
    shortNameJs2: "JDE",
    shortNameRus: "Иуд.",
    fullNameRus: "Иуды",
  },
  {
    shortNameJs1: "Rev",
    shortNameJs2: "REV",
    shortNameRus: "Откр.",
    fullNameRus: "Откровение",
  },
];

const verseDouble = [
  "GEN 34",
  "EXO 17",
  "LEV 11",
  "NUM 10",
  "DEU 3",
  "JOS 7",
  "JDG 18",
  "1SA 30",
  "1KI 8",
  "2KI 17",
  "1CH 23",
  "2CH 36",
  "JOB 6",
  "PSA 7",
  "PSA 71",
  "PSA 119",
  "PRO 21",
  "ISA 18",
  "JER 2",
  "JER 43",
  "EZE 22",
  "DAN 9",
  "ZEC 8",
  "MAT 24",
  "LUK 2",
  "LUK 24",
  "ACT 3",
  "ROM 3",
  "2CO 11",
  "HEB 3",
  "REV 18",
];
